"use client";

import Link from "next/link";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, Search } from "lucide-react";
import { toast } from "sonner";
import { Badge, Button, Card, CardContent, CardHeader, EmptyState, Pagination, Select, TableRowSkeleton } from "@/components/ui";
import { discountsApi, getApiError } from "@/services/api";
import { safeDateFormat } from "@/lib/utils";

export default function DiscountsPage() {
  const [page, setPage] = useState(1); const [q, setQ] = useState(""); const [propFirmId, setPropFirmId] = useState<number | "">(""); const qc = useQueryClient();
  const firmsQuery = useQuery({ queryKey: ["prop-firms"], queryFn: discountsApi.getPropFirms });
  const query = useQuery({ queryKey: ["discounts", page, q, propFirmId], queryFn: () => discountsApi.getAll({ page, limit: 10, q, propFirmId }) });
  const deleteMutation = useMutation({ mutationFn: discountsApi.delete, onSuccess: () => { toast.success("کد حذف شد"); qc.invalidateQueries({ queryKey: ["discounts"] }); }, onError: (error) => toast.error(getApiError(error)) });
  const toggleMutation = useMutation({ mutationFn: ({ id, isActive }: { id: number; isActive: boolean }) => discountsApi.update(id, { isActive }), onSuccess: () => { toast.success("وضعیت کد به‌روزرسانی شد"); qc.invalidateQueries({ queryKey: ["discounts"] }); }, onError: (error) => toast.error(getApiError(error)) });
  return <div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">مدیریت تخفیف‌ها</h1><p className="text-sm text-muted-foreground">دسته‌بندی تخفیف‌ها فقط بر اساس پراپ فرم انجام می‌شود.</p></div><Link href="/dashboard/discounts/create"><Button><Plus className="h-4 w-4" />ایجاد</Button></Link></div><Card><CardHeader><div className="grid gap-3 md:grid-cols-[1fr_260px]"><div className="relative"><Search className="absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input className="input pr-10" placeholder="جستجو در عنوان، کد یا پراپ فرم..." value={q} onChange={(e) => { setQ(e.target.value); setPage(1); }} /></div><Select value={propFirmId} onChange={(e: React.ChangeEvent<HTMLSelectElement>) => { setPropFirmId(e.target.value ? Number(e.target.value) : ""); setPage(1); }}><option value="">همه پراپ فرم‌ها</option>{(firmsQuery.data ?? []).map((firm) => <option key={firm.id} value={firm.id}>{firm.name}</option>)}</Select></div></CardHeader><CardContent className="overflow-x-auto p-0"><table className="data-table"><thead><tr><th>عنوان</th><th>کد</th><th>پراپ فرم</th><th>درصد</th><th>استفاده</th><th>انقضا</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>{query.isLoading && Array.from({ length: 5 }).map((_, i) => <TableRowSkeleton key={i} cols={8} />)}{(query.data?.items ?? []).map((item) => <tr key={item.id}><td className="font-medium">{item.title}</td><td><code className="rounded bg-muted px-2 py-1">{item.code}</code></td><td>{item.propFirm?.name ?? item.propFirmId}</td><td>{item.discountPercent}%</td><td>{item.usageCount}</td><td>{safeDateFormat(item.expiresAt, { dateStyle: "medium" }, "بدون انقضا")}</td><td><Badge variant={item.isActive ? "success" : "warning"}>{item.isActive ? "فعال" : "غیرفعال"}</Badge></td><td className="flex flex-wrap gap-2"><Link href={`/dashboard/discounts/edit/${item.id}`}><Button size="sm" variant="secondary">ویرایش</Button></Link><Button size="sm" variant="outline" loading={toggleMutation.isPending} onClick={() => toggleMutation.mutate({ id: item.id, isActive: !item.isActive })}>{item.isActive ? "غیرفعال" : "فعال"}</Button><Button size="sm" variant="danger" loading={deleteMutation.isPending} onClick={() => confirm("حذف شود؟") && deleteMutation.mutate(item.id)}>حذف</Button></td></tr>)}</tbody></table>{!query.isLoading && !query.data?.items.length && <EmptyState />}</CardContent><Pagination page={page} pages={query.data?.pages ?? 1} onChange={setPage} /></Card></div>;
}
