"use client";

import { useQuery } from "@tanstack/react-query";
import { Activity, BarChart3, Gift, Megaphone, RadioTower, Share2, Ticket, Users } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card, CardContent, CardHeader, EmptyState, StatCardSkeleton } from "@/components/ui";
import { analyticsApi } from "@/services/api";
import { formatNumber } from "@/lib/utils";

function Metric({ title, value, subtitle, icon }: { title: string; value: string | number; subtitle?: string; icon?: React.ReactNode }) {
  return <div className="stat-card"><div className="flex items-center justify-between gap-3"><p className="text-sm text-muted-foreground">{title}</p><div className="rounded-xl bg-primary/10 p-2 text-primary">{icon}</div></div><p className="mt-3 text-2xl font-bold">{typeof value === "number" ? formatNumber(value) : value}</p>{subtitle && <p className="mt-1 text-xs text-muted-foreground">{subtitle}</p>}</div>;
}
function Progress({ label, value }: { label: string; value: number }) { return <div className="space-y-2"><div className="flex justify-between text-xs"><span>{label}</span><span>{value}%</span></div><div className="h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-primary" style={{ width: `${Math.min(100, Math.max(0, value))}%` }} /></div></div>; }
function ChartCard({ title, data, type = "area" }: { title: string; data: Array<{ date: string; count: number }>; type?: "area" | "bar" }) { return <Card><CardHeader><h2 className="flex items-center gap-2 font-semibold"><BarChart3 className="h-4 w-4" />{title}</h2></CardHeader><CardContent className="h-72">{data.length ? <ResponsiveContainer width="100%" height="100%">{type === "bar" ? <BarChart data={data}><CartesianGrid strokeDasharray="3 3" opacity={0.2} /><XAxis dataKey="date" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Bar dataKey="count" fill="hsl(var(--primary))" radius={[6,6,0,0]} /></BarChart> : <AreaChart data={data}><CartesianGrid strokeDasharray="3 3" opacity={0.2} /><XAxis dataKey="date" tick={{ fontSize: 10 }} /><YAxis tick={{ fontSize: 10 }} /><Tooltip /><Area type="monotone" dataKey="count" stroke="hsl(var(--primary))" fill="hsl(var(--primary))" fillOpacity={0.18} /></AreaChart>}</ResponsiveContainer> : <EmptyState />}</CardContent></Card>; }

export default function AnalyticsPage() {
  const query = useQuery({ queryKey: ["analytics-dashboard"], queryFn: analyticsApi.dashboard });
  const d = query.data?.data;
  if (query.isLoading) return <div className="grid gap-4 md:grid-cols-3">{Array.from({ length: 9 }).map((_, i) => <StatCardSkeleton key={i} />)}</div>;
  if (!d) return <EmptyState />;
  return <div className="space-y-6"><div className="page-header"><div><h1 className="section-title">گزارشات و آمار حرفه‌ای</h1><p className="text-sm text-muted-foreground">داشبورد کامل کاربران، دعوت‌ها، تخفیف‌ها، قرعه‌کشی، عضویت اجباری، پیام همگانی و گروه‌ها.</p></div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Users />} title="کل کاربران" value={d.users.totalUsers} subtitle={`امروز: ${formatNumber(d.users.activeToday)}`} /><Metric icon={<Activity />} title="فعال هفته" value={d.users.activeWeek} subtitle={`فعال ماه: ${formatNumber(d.users.activeMonth)}`} /><Metric icon={<Share2 />} title="کل دعوت‌ها" value={d.referrals.totalInvites} subtitle={`موفق: ${formatNumber(d.referrals.successful)}`} /><Metric icon={<Ticket />} title="بلیت فروخته‌شده" value={d.lotteries.ticketsSold} subtitle={`امتیاز مصرف‌شده: ${formatNumber(d.lotteries.pointsSpent)}`} /></div>
    <div className="grid gap-4 md:grid-cols-3"><Card><CardHeader><h2 className="font-semibold">کاربران</h2></CardHeader><CardContent className="space-y-3"><Metric icon={<Users />} title="فعال امروز" value={d.users.activeToday} /><Metric icon={<Users />} title="فعال ماه" value={d.users.activeMonth} /><Progress label="سهم کاربران فعال ماه" value={d.users.totalUsers ? Math.round((d.users.activeMonth / d.users.totalUsers) * 100) : 0} /></CardContent></Card><Card><CardHeader><h2 className="font-semibold">دعوت دوستان</h2></CardHeader><CardContent className="space-y-3"><Metric icon={<Share2 />} title="دعوت موفق" value={d.referrals.successful} /><Progress label="نرخ تبدیل دعوت" value={d.referrals.conversionRate} /><div className="space-y-2">{d.referrals.topReferrers.map((item) => <div key={item.referrerId} className="flex justify-between rounded-lg bg-muted/40 p-2 text-sm"><span>{item.user?.firstName ?? item.referrerId}</span><span>{item._count._all} دعوت</span></div>)}</div></CardContent></Card><Card><CardHeader><h2 className="font-semibold">عضویت اجباری</h2></CardHeader><CardContent className="space-y-3"><Metric icon={<RadioTower />} title="کانال‌ها" value={d.forceJoin.channels} /><Metric icon={<RadioTower />} title="گروه‌ها" value={d.forceJoin.groups} /><Metric icon={<Users />} title="کاربران تاییدشده" value={d.forceJoin.verifiedUsers} /></CardContent></Card></div>
    <div className="grid gap-4 xl:grid-cols-3"><Card><CardHeader><h2 className="font-semibold">کد تخفیف</h2></CardHeader><CardContent className="space-y-2">{d.discounts.topUsage.map((item) => <div key={item.id} className="rounded-lg bg-muted/40 p-3"><p className="font-medium">{item.title}</p><p className="text-xs text-muted-foreground">{item.propFirm?.name} · استفاده: {formatNumber(item.usageCount)}</p></div>)}</CardContent></Card><Card><CardHeader><h2 className="font-semibold">بیشترین کلیک</h2></CardHeader><CardContent className="space-y-2">{d.discounts.topClicks.map((item) => <div key={item.discountCodeId} className="flex justify-between rounded-lg bg-muted/40 p-3 text-sm"><span>{item.discountCode?.title ?? item.discountCodeId}</span><span>{formatNumber(item.clicks)} کلیک</span></div>)}</CardContent></Card><Card><CardHeader><h2 className="font-semibold">قرعه‌کشی</h2></CardHeader><CardContent className="space-y-3"><Metric icon={<Ticket />} title="تعداد قرعه‌کشی‌ها" value={d.lotteries.total} /><Metric icon={<Users />} title="شرکت‌کنندگان" value={d.lotteries.participants} /><Metric icon={<Ticket />} title="شانس کل" value={d.lotteries.totalChance} /><p className="text-xs text-muted-foreground">بیشترین شرکت‌کننده: {d.lotteries.topLottery?.lottery.title ?? "-"}</p></CardContent></Card></div>
    <div className="grid gap-4 md:grid-cols-2"><Card><CardHeader><h2 className="font-semibold">پیام همگانی</h2></CardHeader><CardContent className="space-y-3"><Metric icon={<Megaphone />} title="پیام‌های ارسالی" value={d.broadcasts.total} /><div className="grid gap-3 sm:grid-cols-2"><Metric icon={<Megaphone />} title="موفق" value={d.broadcasts.success} /><Metric icon={<Megaphone />} title="ناموفق" value={d.broadcasts.failed} /></div><Progress label="نرخ موفقیت" value={d.broadcasts.successRate} /></CardContent></Card><Card><CardHeader><h2 className="font-semibold">گروه‌ها</h2></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><Metric icon={<RadioTower />} title="تایید شده" value={d.groups.approved} /><Metric icon={<RadioTower />} title="فعال" value={d.groups.active} /></CardContent></Card></div>
    <div className="grid gap-4 xl:grid-cols-2"><ChartCard title="رشد کاربران" data={d.charts.dailyUsers} /><ChartCard title="رشد دعوت‌ها" data={d.charts.dailyReferrals} type="bar" /><ChartCard title="رشد استفاده از کد تخفیف" data={d.charts.dailyDiscountClicks} /><ChartCard title="رشد شرکت در قرعه‌کشی" data={d.charts.dailyLotteryEntries} type="bar" /></div>
  </div>;
}
